name: Java CI Pipeline


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      
      - name: Build Java Program
        run: javac HelloWorld.java

      
      - name: Run Java Program
        run: java HelloWorld

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'


      - name: Run Test
        run: |
          echo "Running HelloWorld.java"
          result=$(java HelloWorld)
          if [ "$result" != "Hello, World!" ]; then
            echo "Test failed: Expected 'Hello, World!', but got '$result'"
            exit 1
          fi
